### ISSUE TITLE
OpenDirectIO race, likely in tests but not sure

### ISSUE THREAD

**Issue by tv42** [bazil/fuse#127]
``` console
$ rm -f fs.test && go test -c ./fs && while ./fs.test -test.parallel=2 -test.v -test.run=TestDirect; do : ; done
```

causes `TestDirectRead` to read zeroes, not "hello, world". This goes away if you isolate `TestDirectRead` from `TestDirectWrite`, either via `-test.parallel=1` or via `-test.run=TestDirectRead`.

`-race` finds nothing useful. Running the write test in a separate process does not seem to trigger the bug.

This bug has been there since the addition of `TestDirectWrite` in a48407a0a698b36ea96199586425867227b586e1.

**Comment by tv42** [comment]
Under the same conditions, with `-race` slowing things down, I'm also getting

```
2016/02/19 14:55:44 FUSE: kernel write error: error="no such file or directory" stack=
goroutine 24 [running]:
bazil.org/fuse.stack(0x0, 0x0)
	/home/tv/go/src/bazil.org/fuse/debug.go:9 +0x89
bazil.org/fuse.(*Conn).respond(0xc8200f2060, 0xc8200103d0, 0x10, 0x10)
	/home/tv/go/src/bazil.org/fuse/fuse.go:1124 +0xa8
bazil.org/fuse.(*Header).respond(0xc820126280, 0xc8200103d0, 0x10, 0x10)
	/home/tv/go/src/bazil.org/fuse/fuse.go:316 +0x1ce
bazil.org/fuse.(*ReleaseRequest).Respond(0xc820126280)
	/home/tv/go/src/bazil.org/fuse/fuse.go:1818 +0x70
bazil.org/fuse/fs.(*Server).handleRequest(0xc821156000, 0x7f13403df9d8, 0xc820078580, 0x7f134244c028, 0x945d40, 0xc82000a480, 0x7f134031f000, 0xc820126280, 0xc8200c3eb8, 0x0, ...)
	/home/tv/go/src/bazil.org/fuse/fs/serve.go:1270 +0x44bf
bazil.org/fuse/fs.(*Server).serve(0xc821156000, 0x7f134031f000, 0xc820126280)
	/home/tv/go/src/bazil.org/fuse/fs/serve.go:845 +0x9c1
bazil.org/fuse/fs.(*Server).Serve.func1(0xc821156000, 0x7f134031f000, 0xc820126280)
	/home/tv/go/src/bazil.org/fuse/fs/serve.go:416 +0x7f
created by bazil.org/fuse/fs.(*Server).Serve
	/home/tv/go/sr
```

which doesn't seem to happen with `-parallel=1`. This may be a separate bug, or part of the same one.

**Comment by tv42** [comment]
The bug seems to go away if you comment out `regPool.Put(m)`, so somebody is holding on to a message too long -- but why wouldn't `-race` notice?

**Comment by tv42** [comment]
Can't reproduce anymore. No output from `-race` either.
