### ISSUE TITLE
mmap error 

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [bazil/fuse#202]
I build a filesystem by great bazil fuse , things all go well except mmap .

```
[root@localhost test]# ./testmmap_cfs 
unexpected fault address 0x7fe55d0f400a
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fe55d0f400a pc=0x48f71f]

goroutine 1 [running]:
runtime.throw(0x4c1a43, 0x5)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc420057de8 sp=0xc420057dc8 pc=0x426b01
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:385 +0x273 fp=0xc420057e38 sp=0xc420057de8 pc=0x4391a3
main.helperMmap()
	/home/zxc/project/src/test/testmmap_cfs.go:30 +0x1ff fp=0xc420057f78 sp=0xc420057e38 pc=0x48f71f
main.main()
	/home/zxc/project/src/test/testmmap_cfs.go:52 +0x20 fp=0xc420057f88 sp=0xc420057f78 pc=0x48f9c0
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc420057fe0 sp=0xc420057f88 pc=0x428372
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420057fe8 sp=0xc420057fe0 pc=0x44f091
```

```
/dev/mapper/centos-root                        50G  9.1G   41G   19% /
devtmpfs                                      3.8G     0  3.8G    0% /dev
tmpfs                                         3.8G   19M  3.8G    1% /dev/shm
tmpfs                                         3.8G   19M  3.8G    1% /run
tmpfs                                         3.8G     0  3.8G    0% /sys/fs/cgroup
/dev/sda1                                    1014M  278M  737M   28% /boot
/dev/mapper/centos-home                       873G   17G  857G    2% /home
tmpfs                                         771M   68K  771M    1% /run/user/0
ContainerFS-e295d77e4073e95880f5aa4232708c1f   16G   14M   16G    1% /mnt/cfs-test1
```

test code:
```
package main

import "syscall"
import "os"
import "log"
import "bazil.org/fuse/syscallx"

const mmapSize = 16 * 4096

var mmapWrites = map[int]byte{
        10:              'a',
        4096:            'b',
        4097:            'c',
        mmapSize - 4096: 'd',
        mmapSize - 1:    'z',
}

func helperMmap() {
        f, err := os.Create("/mnt/cfs-test1/child")
        if err != nil {
                log.Fatalf("Create: %v", err)
        }
        defer f.Close()

        data, err := syscall.Mmap(int(f.Fd()), 0, mmapSize, syscall.PROT_READ|syscall.PROT_WRITE, syscall.MAP_SHARED)
        if err != nil {
                log.Fatalf("Mmap: %v", err)
        }
        for i, b := range mmapWrites {
                data[i] = b
        }

        if err := syscallx.Msync(data, syscall.MS_SYNC); err != nil {
                log.Fatalf("Msync: %v", err)
        }

        if err := syscall.Munmap(data); err != nil {
                log.Fatalf("Munmap: %v", err)
        }

        if err := f.Sync(); err != nil {
                log.Fatalf("Fsync = %v", err)
        }

        err = f.Close()
        if err != nil {
                log.Fatalf("Close: %v", err)
        }
}

func main(){
	helperMmap()
}
```

**Comment by zhengxiaochuan-3** [comment]
And when mmap read an existing file on my fs , goes to "Mmap: no such device" 

```
        f, err := os.Open("/mnt/cfs-test1/pack-d94c4327e9e68d6d4cdc66de03d7cbd4df907a34.idx")
        if err != nil {
                log.Fatalf("Open: %v", err)
        }
        defer f.Close()
        data, err := syscall.Mmap(int(f.Fd()), 0, 4, syscall.PROT_READ, syscall.MAP_SHARED)
        if err != nil {
                log.Fatalf("Mmap: %v", err)
                return
        }

```

**Comment by themester** [comment]
@zhengxiaochuan-3 do not use `Open`.

**Comment by themester** [comment]
@zhengxiaochuan-3 do not use `Open`.
```go
        f, err := os.OpenFile("/mnt/cfs-test1/pack-d94c4327e9e68d6d4cdc66de03d7cbd4df907a34.idx", os.O_RDWR, 0)
        if err != nil {
                log.Fatalf("Open: %v", err)
        }
        defer f.Close()
        data, err := syscall.Mmap(int(f.Fd()), 0, 4, syscall.PROT_READ|syscall.PROT_WRITE, syscall.MAP_SHARED)
        if err != nil {
                log.Fatalf("Mmap: %v", err)
                return
        }
        syscall.Munmap(data) // <- do not forget this line
```

**Comment by zhengxiaochuan-3** [comment]
this code works well on both myfs and local filesystem in linux 👍 

```
package main

import "syscall"
import "os"
import "log"
import "bazil.org/fuse/syscallx"
import "fmt"
const mmapSize = 16 * 4096

var mmapWrites = map[int]byte{
        10:              'a',
        4096:            'b',
        4097:            'c',
        mmapSize - 4096: 'd',
        mmapSize - 1:    'z',
}

func helperMmap() {
/*        f, err := os.Create("/mnt/cfs-test1/child")
        if err != nil {
                log.Fatalf("Create: %v", err)
        }
*/

	f, err := os.OpenFile("/mnt/cfs-test1/childnew", os.O_RDWR|os.O_CREATE, 0755)
        if err != nil {
                log.Fatalf("Open: %v", err)
        }


        defer f.Close()

	for i:=0;i<mmapSize;i++ {
		_, err = f.Write([]byte("1"))
        	if err!=nil {
                	log.Fatalf("Write: %v", err)
        	}
	}
	f.Sync()

        data, err := syscall.Mmap(int(f.Fd()), 0, mmapSize, syscall.PROT_READ|syscall.PROT_WRITE, syscall.MAP_SHARED)
        if err != nil {
                log.Fatalf("Mmap: %v", err)
        }
        for i, b := range mmapWrites {
		fmt.Printf("i=%v",i)
                data[i] = b
        }

        if err := syscallx.Msync(data, syscall.MS_SYNC); err != nil {
                log.Fatalf("Msync: %v", err)
        }

        if err := syscall.Munmap(data); err != nil {
                log.Fatalf("Munmap: %v", err)
        }

        if err := f.Sync(); err != nil {
                log.Fatalf("Fsync = %v", err)
        }

        err = f.Close()
        if err != nil {
                log.Fatalf("Close: %v", err)
        }
}

func main(){
	helperMmap()
}
```

this code works well on linux ,   get "Mmap: no such device" on my fs 

```
package main

import "syscall"
import "os"
import "log"
const mmapSize = 16 * 4096

var mmapWrites = map[int]byte{
        10:              'a',
        4096:            'b',
        4097:            'c',
        mmapSize - 4096: 'd',
        mmapSize - 1:    'z',
}

func helperMmap() {
        f, err := os.OpenFile("/mnt/cfs-test1/child", os.O_RDWR|os.O_CREATE, 0755)
        if err != nil {
                log.Fatalf("Open: %v", err)
        }
        defer f.Close()
        data, err := syscall.Mmap(int(f.Fd()), 0, mmapSize, syscall.PROT_READ|syscall.PROT_WRITE, syscall.MAP_SHARED)
        if err != nil {
                log.Fatalf("Mmap: %v", err)
                return
        }

        if err := syscall.Munmap(data); err != nil {
                log.Fatalf("Munmap: %v", err)
        }

        if err := f.Sync(); err != nil {
                log.Fatalf("Fsync = %v", err)
        }

        err = f.Close()
        if err != nil {
                log.Fatalf("Close: %v", err)
        }
}

func main() {
        helperMmap()
}

```

**Comment by zhengxiaochuan-3** [comment]
@themester

**Comment by zhengxiaochuan-3** [comment]
Turns out I returned an unexpected  OpenDirectIO flag for Open by mistake .
by reading linux kernel code ,OpenDirectIO  exclusive with syscall.MAP_SHARED  

I`m closing this issue ... 

thanks @themester

**Comment by tv42** [comment]
Yeah, shared mmap asks to share page cache between processes. Direct IO asks to not use page cache. Something will fail, somehow; how obviously and cleanly they fail is a different question.

I see no mention of OpenDirectIO in the provided example programs, so this feels like it's not easily reproducible. Also, along the way this issue seems to have talked about several different behaviors (SIGBUS vs "no such device").

The talk about os.Create vs os.OpenFile, and implementing Fsync, seem red herrings and not related to any bugs/unexpected behavior observed.

Please give a complete example of what happened and how it was unexpected and we can sort out whether it's a bug of a programmer error. For example, I would expect you to see a SIGBUS or similar if you write to write to a read-only mmap, and that part has nothing to with FUSE.

**Comment by zhengxiaochuan-3** [comment]
@tv42   The OpenDirectIO Flag is added by mistake on my fuse handler "NodeOpener"

```
func (f *File) Open(ctx context.Context, req *bfuse.OpenRequest, resp *bfuse.OpenResponse) (fs.Handle, error) {
   // ....
   resp.Flags = bfuse.OpenDirectIO     //  bug here
}
```
