### ISSUE TITLE
bugShortKernelWrite can trigger on FUSE connection abort

### ISSUE THREAD

**Issue by tv42** [bazil/fuse#25]
This was triggered either by a `fusermount -u` or `echo 1 >/sys/fs/fuse/connections/XXX/abort`, not sure which.

```
2014/08/06 11:51:52 FUSE: short kernel write: written=-1/24 error="no such file or directory" stack=
goroutine 68612 [running]:
bazil.org/fuse.stack(0x0, 0x0)
    /home/tv/go/src/bazil.org/fuse/debug.go:9 +0x80
bazil.org/fuse.(*Conn).respond(0xc20800e040, 0xc2080a14f8, 0x18)
    /home/tv/go/src/bazil.org/fuse/fuse.go:848 +0x155
bazil.org/fuse.(*WriteRequest).Respond(0xc208004480, 0xc208036560)
    /home/tv/go/src/bazil.org/fuse/fuse.go:1567 +0x78
bazil.org/fuse/fs.(*serveConn).serve(0xc2080480a0, 0x7fa37ea88a98, 0xc208004480)
    /home/tv/go/src/bazil.org/fuse/fs/serve.go:1116 +0x2b0a
created by bazil.org/fuse/fs.(*Server).Serve
    /home/tv/go/src/bazil.org/fuse/fs/serve.go:335 +0x5b0
```

The client side saw ECONNABORTED from a write.

Should probably catch that case and handle cleaner; add a stress test.

**Comment by tv42** [comment]
I haven't seen this in the years since. Probably a race fixed by the rio/wio locks?
