### ISSUE TITLE
panic in handler for Statfs

### ISSUE THREAD

**Issue by marius-enlock** [bazil/fuse#303]
Hello,

I keep bumping into random panics for my program, they all originate from Statfs.

OS:
`Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
`
Arch: x86_64

Fusermount3 --version:
`fusermount3 version: 3.10.5
`

Bazil fuse version from the go.mod file:
`	bazil.org/fuse v0.0.0-20230120002735-62a210ff1fd5
`

My implementation:
```
func (efs *FileSystem) Statfs(_ context.Context, req *fuse.StatfsRequest, resp *fuse.StatfsResponse) error {
	efs.logger.Debug("Filesystem statfs")
	fi := syscall.Statfs_t{}

	err := syscall.Statfs(efs.rootPath, &fi)
	if err != nil {
		efs.logger.Error("Failed to stat path", "error", err)
		return err
	}

	setStatfsResponse(resp, fi)

	return nil
}

func setStatfsResponse(resp *fuse.StatfsResponse, fi syscall.Statfs_t) {
	if resp == nil {
		resp = &fuse.StatfsResponse{}
	}
	resp.Bsize = uint32(fi.Bsize)
	resp.Bavail = fi.Bavail
	resp.Bfree = fi.Bfree
	resp.Blocks = fi.Blocks
	resp.Bsize = uint32(fi.Bsize)
	resp.Ffree = fi.Ffree
	resp.Files = fi.Files
	resp.Frsize = uint32(fi.Frsize)
	resp.Namelen = uint32(64) // We allow only 64 characters in the name.
}
```

The stacktrace:

```
Line: t=2024-01-11T16:10:44+0200 lvl=dbug msg="Filesystem statfs" service=drive
Line: t=2024-01-11T16:10:44+0200 lvl=dbug msg="FUSE DEBUG" service=drive msg="-> [ID=0x188] Statfs blocks=131134179/143320291/239534374 files=58388961/60915712 bsize=4096 frsize=4096 namelen=64"
Line: 2024/01/11 16:10:44 fuse: panic in handler for Statfs [ID=0x188 Node=0x1 Uid=1000 Gid=1000 Pid=1685593]: runtime error: invalid memory address or nil pointer dereference
Line: goroutine 8187 [running]:
Line: bazil.org/fuse/fs.(*Server).serve.func2()
Line: 	/home/code/fuse/fs/serve.go:1004 +0x119
Line: panic({0x13d4480?, 0x3a6b050?})
Line: 	/usr/local/go/src/runtime/panic.go:914 +0x21f
Line: bazil.org/fuse.(*Conn).writeToKernel(0x42e645?, {0xc000510a20, 0x60, 0x60})
Line: 	/home/code/fuse/fuse.go:1172 +0x68
Line: bazil.org/fuse.(*Conn).respond(0x470369?, {0xc000510a20?, 0x137fe60?, 0x101?})
Line: 	/home/code/fuse/fuse.go:1187 +0x1c
Line: bazil.org/fuse.(*Header).respond(0xc00027f710, {0xc000510a20?, 0x1000?, 0xe470126?})
Line: 	/home/code/fuse/fuse.go:296 +0x34
Line: bazil.org/fuse.(*StatfsRequest).Respond(0xc00027f710, 0xc00323c840)
Line: 	/home/code/fuse/fuse.go:1495 +0x13d
Line: bazil.org/fuse/fs.(*Server).handleRequest(0xc00012a000, {0x162ccd8, 0xc002dc4690}, {0x1626120?, 0xc000b78000?}, 0x2?, {0x162be10?, 0xc00027f710?}, 0xc000605f08)
Line: 	/home/code/fuse/fs/serve.go:1070 +0x125
Line: bazil.org/fuse/fs.(*Server).serve(0xc00012a000, {0x162be10, 0xc00027f710})
Line: 	/home/code/fuse/fs/serve.go:1025 +0x5b1
Line: bazil.org/fuse/fs.(*Server).Serve.func1()
Line: 	/home/code/fuse/fs/serve.go:522 +0x5a
Line: created by bazil.org/fuse/fs.(*Server).Serve in goroutine 1
Line: 	/home/code/fuse/fs/serve.go:520 +0x373
Line: t=2024-01-11T16:10:44+0200 lvl=dbug msg="FUSE DEBUG" service=drive msg="-> [ID=0x188] Statfs error=EIO: handler panicked: runtime error: invalid memory address or nil pointer dereference"
Line: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Line: 	panic: runtime error: invalid memory address or nil pointer dereference
Line: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa9d188]
Line: 
Line: goroutine 8187 [running]:
Line: bazil.org/fuse.(*Conn).writeToKernel(0x42e645?, {0xc0030c3400, 0x10, 0x10})
Line: 	/home/code/fuse/fuse.go:1172 +0x68
Line: bazil.org/fuse.(*Conn).respond(0x470369?, {0xc0030c3400?, 0x137fe60?, 0xc0030cee01?})
Line: 	/home/code/fuse/fuse.go:1187 +0x1c
Line: bazil.org/fuse.(*Header).respond(0xc00027f710, {0xc0030c3400?, 0xc0030d08e0?, 0x0?})
Line: 	/home/code/fuse/fuse.go:296 +0x34
Line: bazil.org/fuse.(*Header).RespondError(0x1?, {0x1628c40?, 0xc0030d08e0?})
Line: 	/home/code/fuse/fuse.go:405 +0x65
Line: bazil.org/fuse/fs.(*Server).serve.func2()
Line: 	/home/code/fuse/fs/serve.go:1012 +0x2d5
Line: panic({0x13d4480?, 0x3a6b050?})
Line: 	/usr/local/go/src/runtime/panic.go:914 +0x21f
Line: bazil.org/fuse.(*Conn).writeToKernel(0x42e645?, {0xc000510a20, 0x60, 0x60})
Line: 	/home/code/fuse/fuse.go:1172 +0x68
Line: bazil.org/fuse.(*Conn).respond(0x470369?, {0xc000510a20?, 0x137fe60?, 0x101?})
Line: 	/home/code/fuse/fuse.go:1187 +0x1c
Line: bazil.org/fuse.(*Header).respond(0xc00027f710, {0xc000510a20?, 0x1000?, 0xe470126?})
Line: 	/home/code/fuse/fuse.go:296 +0x34
Line: bazil.org/fuse.(*StatfsRequest).Respond(0xc00027f710, 0xc00323c840)
Line: 	/home/code/fuse/fuse.go:1495 +0x13d
Line: bazil.org/fuse/fs.(*Server).handleRequest(0xc00012a000, {0x162ccd8, 0xc002dc4690}, {0x1626120?, 0xc000b78000?}, 0x2?, {0x162be10?, 0xc00027f710?}, 0xc000605f08)
Line: 	/home/code/fuse/fs/serve.go:1070 +0x125
Line: bazil.org/fuse/fs.(*Server).serve(0xc00012a000, {0x162be10, 0xc00027f710})
Line: 	/home/code/fuse/fs/serve.go:1025 +0x5b1
Line: bazil.org/fuse/fs.(*Server).Serve.func1()
Line: 	/home/code/fuse/fs/serve.go:522 +0x5a
Line: created by bazil.org/fuse/fs.(*Server).Serve in goroutine 1
Line: 	/home/code/fuse/fs/serve.go:520 +0x373
```

I am a bit confused of why this happens, any input is appreciated.

**Comment by tv42** [comment]
It would be helpful in general to share a complete program, and the workload that makes it fail.

Copy-pasting your Statfs and setStatfsResponse into examples/hellofs, commenting out the dangling efs.logger references, mounting that and running `stat --file-system mnt` works just fine.

**Comment by marius-enlock** [comment]
I have a quite complex setup of the file system getting mounted from a grpc server that is run as a binary from a sub-process that has stdin/stdout piped in order to be used for communicating.

After incrementally trying to reproduce a minimum code example I can confirm that: 
- just the file system by itself (with stripped down logic) doesn't panic
- just the file system (with stripped down logic) that is run as a binary from a sub-process by itself doesn't panic

I will close the issue, as I think the problem might originate from somewhere else.

I will re-open with a minimal reproducing example if I it will be the case. 

Thank you for the input!
